<?php
session_start(); 
include"menu.php"  ?>
<div class="container">
	
<br>
	<div class="card mb-3">
	  <div style="height: 350px; background-size:cover; background-image: url('gym.jpg')" class="card-img-top img-fluide" alt="..."></div>
	  <div class="card-body">
	    <h3 class="card-title">Association sportive JEMAL</h3>
	    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum..</p>
	  </div>
	</div>
	<div class="row">
		<div class="col-12">
			<h1 style="text-align: center;">Les fondateurs</h1>	
		</div>	
	</div>

	<div class="row">
		<div class="col-12 col-md-6 col-lg-4">
			<!-- Card -->
			<div class="card testimonial-card">

	  <!-- Background color -->
	  		<div class="card-up indigo lighten-1"></div>

	  <!-- Avatar -->
	  		<div class="avatar mx-auto white">
	   			 <img src="fonda1.jpg" style="width:200px; height:200px" class="rounded-circle" alt="woman avatar">
	  		</div>

	  <!-- Content -->
	  		<div class="card-body">
	    <!-- Name -->
	    	<h4 class="card-title">JEMAL MOHCINE</h4>
	    	<hr>
	    <!-- Quotation -->
	    	<p><i class="fas fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, adipisci</p>
	  		</div>
	  		</div>

		
	<!-- Card -->	
		</div>	

		<div class="col-12 col-md-6 col-lg-4">
			<!-- Card -->
			<div class="card testimonial-card">

	  <!-- Background color -->
	  		<div class="card-up indigo lighten-1"></div>

	  <!-- Avatar -->
	  		<div class="avatar mx-auto white">
	   			 <img src="fonda2.jpg" style="width:200px; height:200px" class="rounded-circle" alt="woman avatar">
	  		</div>

	  <!-- Content -->
	  		<div class="card-body">
	    <!-- Name -->
	    	<h4 class="card-title">RONIE DROUF</h4>
	    	<hr>
	    <!-- Quotation -->
	    	<p><i class="fas fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, adipisci</p>
	  		</div>
	  		</div>

		
	<!-- Card -->	
		</div>	

		<div class="col-12 col-md-6 col-lg-4">
			<!-- Card -->
			<div class="card testimonial-card">

	  <!-- Background color -->
	  		<div class="card-up indigo lighten-1"></div>

	  <!-- Avatar -->
	  		<div class="avatar mx-auto white">
	   			 <img src="fonda3.jpg" style="width:200px; height:200px" class="rounded-circle" alt="woman avatar">
	  		</div>

	  <!-- Content -->
	  		<div class="card-body">
	    <!-- Name -->
	    	<h4 class="card-title">DURRAH MOHAMED</h4>
	    	<hr>
	    <!-- Quotation -->
	    	<p><i class="fas fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, adipisci</p>
	  		</div>
	  		</div>

		
	<!-- Card -->	
		</div>	
	</div>
	<br>

	<div class="row">
		<div class="col-12">
			<h1 style="text-align: center;">Les sponsors</h1>	
		</div>	
	</div>

	<div class="row">
		<div class="col-12 col-md-6 col-lg-4" style="margin-bottom: 30px;">
			<!-- Card -->
			<div class="card">

			  <!-- Card image -->
			  <img class="card-img-top" src="https://s3images.coroflot.com/user_files/individual_files/88106_nhkcdbydmrcpscg0prddut6r5.jpg" alt="Card image cap" style="height: 250px;">

			  <!-- Card content -->
			  <div class="card-body">

			    <!-- Title -->
			    <h4 class="card-title"><a>PASSAGE FITNESS</a></h4>
			    <!-- Text -->
			    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			    <!-- Button -->
			  </div>

			</div>
			<!-- Card -->
		</div>

		<div class="col-12 col-md-6 col-lg-4">
			<!-- Card -->
			<div class="card">

			  <!-- Card image -->
			  <img class="card-img-top" src="https://nike.brickworksoftware.com/assets?format=webp&source=https://cdn.filepicker.io/api/file/958uDtjiQjq8lMILaGWk" style="height: 250px;" alt="Card image cap">

			  <!-- Card content -->
			  <div class="card-body">

			    <!-- Title -->
			    <h4 class="card-title"><a>NIKE STORE</a></h4>
			    <!-- Text -->
			    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			    <!-- Button -->
			  </div>

			</div>
			<!-- Card -->
		</div>

		<div class="col-12 col-md-6 col-lg-4">
			<!-- Card -->
			<div class="card">

			  <!-- Card image -->
			  <img class="card-img-top" src="https://www.dreamjob.ma/wp-content/uploads/2019/01/pablo-33-750x375.png" style="height: 250px;">

			  <!-- Card content -->
			  <div class="card-body">

			    <!-- Title -->
			    <h4 class="card-title"><a>CITY CLUB</a></h4>
			    <!-- Text -->
			    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
			    <!-- Button -->
			  </div>

			</div>
			<!-- Card -->
		</div>

	</div>
<!-- Card -->
	


</div>

<?php include"footer.php"; ?>