<?php include "menu.php"; ?>

  <div class="view intro-2" >
    <div class="full-bg-img">
      <div class="mask rgba-black-strong flex-center">
        <div class="container">
          <div class="white-text text-center wow fadeInUp">
            <h1 class="bounce animated"> welcome </h1>
            <h5>Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.</h5>
            <br>
            <p>A muscle is like a car. If you want it to run well early in the morning, you have to warm it up. </p>
          </div>
        </div>
      </div>
    </div>
  </div>

</header>
<!--Main Navigation-->

<!--Main Layout-->
<main  style="background: #696969; padding-top: 80px">

  <div class="container">
      <form action="inscrire.php" method="post">
        <div class="form-group">
         <label >Nom complet</label>
          <input type="text" class="form-control"  placeholder="Enter votre nom" name="nom">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="mail">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="password">
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">repeter votre mot de passe</label>
          <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="repeterpassword">
        </div>
        <div class="form-group form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
          <button type="submit" class="btn btn-primary" name="submit">s'inscrire</button>
</form>

  </div>
  <br>
  <br>

</main>
<?php include'footer.php';  ?>

<!--Main Layout-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
</body>

</html>
